
name = input("Wpisz swoje imie: ")
surname = input("Wpisz swoje nazwisko: ")
age = input("Wpisz swój wiek: ")
phone = input("Podaj numer telefonu: ")
location = input("Podaj miejsce zamieszkania: ")

print("             ")
print("-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=")
print("          ")
print("Imię: ", name)
print("Nazwisko: ", surname)
print("Wiek: ", age)
print("Numer telefonu: ", phone)
print("Miejsce zamieszkania: ", location)
